### ISSUE TITLE
Create notification service

### ISSUE THREAD

**Issue by Ekan5h** [CS305-software-Engineering/GarbageCollection#11]
* Prompt notification (When collector starts journey)
* Alert Notification (When the collector is near)
* Notification model in backend DB

**Comment by hansinahuja** [comment]
Added push notifications for disposer

**Comment by parasgoyal12** [comment]
Add push notifications to Disposer and Send Responses to Collector API

**Comment by hansinahuja** [comment]
Added foreground notification

**Comment by hansinahuja** [comment]
Set up FCM
