### ISSUE TITLE
Create Login for Various User classes

### ISSUE THREAD

**Issue by parasgoyal12** [CS305-software-Engineering/GarbageCollection#4]
U1- Admin Interface
U2- Garbage Collectore
U3- Garbage Disposer

Authentication type (Social Accounts, Local) need to be discussed....

**Comment by parasgoyal12** [comment]
Admin Login Completed

**Comment by parasgoyal12** [comment]
* Login API completed.
* Registration API for disposer completed
*  Registration API for collector (In Progress)

**Comment by Ekan5h** [comment]
Login and Signup integration with Collector and Disposer apps completed
